In [74]:
PixPorMunicipio = "https://olinda.bcb.gov.br/olinda/servico/Pix_DadosAbertos/versao/v1/odata/TransacoesPixPorMunicipio(DataBase=@DataBase)?@DataBase=''&$top=100&$format=json&$select=Estado,Regiao,VL_RecebedorPF"
ChavesPix = "https://olinda.bcb.gov.br/olinda/servico/Pix_DadosAbertos/versao/v1/odata/ChavesPix(Data=@Data)?@Data='2023-09-01'&$top=100&$format=json&$select=Nome,NaturezaUsuario,TipoChave"

In [47]:
import pandas as pd
import requests
import json

In [75]:
def requisicao_api(ppm,cp):
  resposta = requests.get(ppm)
  resposta2 = requests.get(cp)
  ##resposta3 = requests.get(cp)

  if(resposta.status_code == 200 and 
    resposta2.status_code == 200):
    dados = resposta.json()
    dados2 = resposta2.json()
         #sucesso na requisição
    dados = resposta.json()
    with open('Municipio.json', 'w', encoding='utf-8') as arquivo:   #salvar arquivo json
      json.dump(dados, arquivo, ensure_ascii=False, indent=4)
    with open('Chaves.json', 'w', encoding='utf-8') as arquivo:   #salvar arquivo json
      json.dump(dados2, arquivo, ensure_ascii=False, indent=4)

In [76]:
requisicao_api(PixPorMunicipio,ChavesPix)

In [77]:
jsondata = pd.read_json('Municipio.json')
jsondata2 = pd.read_json('chaves.json')

In [ ]:
jsondata

,@odata.context,value
0,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'PARANÁ', 'Regiao': 'SUL', 'VL_Rece..."
1,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'PARANÁ', 'Regiao': 'SUL', 'VL_Rece..."
2,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'MARANHÃO', 'Regiao': 'NORDESTE', '..."
3,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'BAHIA', 'Regiao': 'NORDESTE', 'VL_..."
4,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'MINAS GERAIS', 'Regiao': 'SUDESTE'..."
...,...,...
95,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'PARANÁ', 'Regiao': 'SUL', 'VL_Rece..."
96,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'BAHIA', 'Regiao': 'NORDESTE', 'VL_..."
97,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'BAHIA', 'Regiao': 'NORDESTE', 'VL_..."
98,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'PARANÁ', 'Regiao': 'SUL', 'VL_Rece..."
99,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Estado': 'BAHIA', 'Regiao': 'NORDESTE', 'VL_..."

In [78]:
jsondata2

,@odata.context,value
0,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'CC CREDIGUAÇU', 'NaturezaUsuario': '..."
1,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'COOP ASCOOB SERTÕES', 'NaturezaUsuar..."
2,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'BCO MODAL S.A.', 'NaturezaUsuario': ..."
3,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'EQUIS BANK', 'NaturezaUsuario': 'PJ'..."
4,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'COOP SICOOB CONFIANÇA', 'NaturezaUsu..."
...,...,...
95,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'BCO BNP PARIBAS BRASIL S A', 'Nature..."
96,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'CCLA PARA DE MINAS', 'NaturezaUsuari..."
97,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'COOPERATIVA DE CRÉDITO SAROM', 'Natu..."
98,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'COOP COOPERFORTE LTDA.', 'NaturezaUs..."
99,https://was-p.bcnet.bcb.gov.br/olinda/servico/...,"{'Nome': 'CC SICOOB ENGECRED', 'NaturezaUsuari..."

In [79]:
Municipio = jsondata['value']
Chaves = jsondata2['value']

In [82]:
muni = pd.json_normalize(Municipio)
chave = pd.json_normalize(Chaves)

In [86]:
muni.head()

   Estado    Regiao  VL_RecebedorPF
0   PIAUÍ  NORDESTE    9.106480e+06
1  PARANÁ       SUL    3.069640e+07
2  PARANÁ       SUL    5.374908e+06
3    PARÁ     NORTE    3.269028e+06
4   BAHIA  NORDESTE    1.270901e+08

In [85]:
chave.head()

                    Nome NaturezaUsuario  TipoChave
0          CC CREDIGUAÇU              PF    Celular
1    COOP ASCOOB SERTÕES              PF    Celular
2         BCO MODAL S.A.              PF    Celular
3             EQUIS BANK              PJ     e-mail
4  COOP SICOOB CONFIANÇA              PF  Aleatória

In [88]:
muni.to_csv("dados.csv", index=False, encoding="utf-8")
chave.to_csv("valores.csv", index=False, encoding="utf-8")

In [89]:
print(muni.isnull().sum())
print(muni.dtypes)
print(chave.isnull().sum())
print(chave.dtypes)

Estado            0
Regiao            0
VL_RecebedorPF    0
dtype: int64
Estado             object
Regiao             object
VL_RecebedorPF    float64
dtype: object
Nome               0
NaturezaUsuario    0
TipoChave          0
dtype: int64
Nome               object
NaturezaUsuario    object
TipoChave          object
dtype: object

In [90]:
muni = muni.rename(columns={"Estado": "estado","Regiao": "Regiao", "VL_RecebedorPF": "Valor Recebedor PF" })
Chave = chave.rename(columns={"Nome": "Nome do PSP", "NaturezaUsuario": "Natureza do Usuário", "TipoChave": "Tipo de Chave"})

In [ ]:
muni

In [91]:
Chave

                     Nome do PSP Natureza do Usuário Tipo de Chave
0                  CC CREDIGUAÇU                  PF       Celular
1            COOP ASCOOB SERTÕES                  PF       Celular
2                 BCO MODAL S.A.                  PF       Celular
3                     EQUIS BANK                  PJ        e-mail
4          COOP SICOOB CONFIANÇA                  PF     Aleatória
..                           ...                 ...           ...
95    BCO BNP PARIBAS BRASIL S A                  PJ        e-mail
96            CCLA PARA DE MINAS                  PJ       Celular
97  COOPERATIVA DE CRÉDITO SAROM                  PF           CPF
98        COOP COOPERFORTE LTDA.                  PF     Aleatória
99            CC SICOOB ENGECRED                  PJ       Celular

[100 rows x 3 columns]

In [60]:
from pymongo import MongoClient

In [ ]:
# Cole aqui a string de conexão do Atlas: NÃO COMPARTILHE SEU USUÁRIO E SENHA
MONGO_URI = "mongodb+srv://:@cluster0.iexbral.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Criar conexão
client = MongoClient(MONGO_URI)

In [67]:
# Criar/selecionar banco de dados
db = client["pix_BCB"]

# Criar/selecionar coleção (tabela no Mongo)
colecao = db["municipop"]

In [68]:
# após a conexão, fazer consulta a um documento da coleção
colecao.find_one()

In [72]:
municipop = muni.to_dict (orient="records")
# Inserindo um novo documento na coleção. O insert_one() insere apenas 1 registro
colecao.insert_many(municipop)

InsertManyResult([ObjectId('68d6f22621e68be5b34eb4b5'), ObjectId('68d6f22621e68be5b34eb4b6'), ObjectId('68d6f22621e68be5b34eb4b7'), ObjectId('68d6f22621e68be5b34eb4b8'), ObjectId('68d6f22621e68be5b34eb4b9'), ObjectId('68d6f22621e68be5b34eb4ba'), ObjectId('68d6f22621e68be5b34eb4bb'), ObjectId('68d6f22621e68be5b34eb4bc'), ObjectId('68d6f22621e68be5b34eb4bd'), ObjectId('68d6f22621e68be5b34eb4be'), ObjectId('68d6f22621e68be5b34eb4bf'), ObjectId('68d6f22621e68be5b34eb4c0'), ObjectId('68d6f22621e68be5b34eb4c1'), ObjectId('68d6f22621e68be5b34eb4c2'), ObjectId('68d6f22621e68be5b34eb4c3'), ObjectId('68d6f22621e68be5b34eb4c4'), ObjectId('68d6f22621e68be5b34eb4c5'), ObjectId('68d6f22621e68be5b34eb4c6'), ObjectId('68d6f22621e68be5b34eb4c7'), ObjectId('68d6f22621e68be5b34eb4c8'), ObjectId('68d6f22621e68be5b34eb4c9'), ObjectId('68d6f22621e68be5b34eb4ca'), ObjectId('68d6f22621e68be5b34eb4cb'), ObjectId('68d6f22621e68be5b34eb4cc'), ObjectId('68d6f22621e68be5b34eb4cd'), ObjectId('68d6f22621e68be5b34eb4ce'), ObjectId('68d6f22621e68be5b34eb4cf'), ObjectId('68d6f22621e68be5b34eb4d0'), ObjectId('68d6f22621e68be5b34eb4d1'), ObjectId('68d6f22621e68be5b34eb4d2'), ObjectId('68d6f22621e68be5b34eb4d3'), ObjectId('68d6f22621e68be5b34eb4d4'), ObjectId('68d6f22621e68be5b34eb4d5'), ObjectId('68d6f22621e68be5b34eb4d6'), ObjectId('68d6f22621e68be5b34eb4d7'), ObjectId('68d6f22621e68be5b34eb4d8'), ObjectId('68d6f22621e68be5b34eb4d9'), ObjectId('68d6f22621e68be5b34eb4da'), ObjectId('68d6f22621e68be5b34eb4db'), ObjectId('68d6f22621e68be5b34eb4dc'), ObjectId('68d6f22621e68be5b34eb4dd'), ObjectId('68d6f22621e68be5b34eb4de'), ObjectId('68d6f22621e68be5b34eb4df'), ObjectId('68d6f22621e68be5b34eb4e0'), ObjectId('68d6f22621e68be5b34eb4e1'), ObjectId('68d6f22621e68be5b34eb4e2'), ObjectId('68d6f22621e68be5b34eb4e3'), ObjectId('68d6f22621e68be5b34eb4e4'), ObjectId('68d6f22621e68be5b34eb4e5'), ObjectId('68d6f22621e68be5b34eb4e6'), ObjectId('68d6f22621e68be5b34eb4e7'), ObjectId('68d6f22621e68be5b34eb4e8'), ObjectId('68d6f22621e68be5b34eb4e9'), ObjectId('68d6f22621e68be5b34eb4ea'), ObjectId('68d6f22621e68be5b34eb4eb'), ObjectId('68d6f22621e68be5b34eb4ec'), ObjectId('68d6f22621e68be5b34eb4ed'), ObjectId('68d6f22621e68be5b34eb4ee'), ObjectId('68d6f22621e68be5b34eb4ef'), ObjectId('68d6f22621e68be5b34eb4f0'), ObjectId('68d6f22621e68be5b34eb4f1'), ObjectId('68d6f22621e68be5b34eb4f2'), ObjectId('68d6f22621e68be5b34eb4f3'), ObjectId('68d6f22621e68be5b34eb4f4'), ObjectId('68d6f22621e68be5b34eb4f5'), ObjectId('68d6f22621e68be5b34eb4f6'), ObjectId('68d6f22621e68be5b34eb4f7'), ObjectId('68d6f22621e68be5b34eb4f8'), ObjectId('68d6f22621e68be5b34eb4f9'), ObjectId('68d6f22621e68be5b34eb4fa'), ObjectId('68d6f22621e68be5b34eb4fb'), ObjectId('68d6f22621e68be5b34eb4fc'), ObjectId('68d6f22621e68be5b34eb4fd'), ObjectId('68d6f22621e68be5b34eb4fe'), ObjectId('68d6f22621e68be5b34eb4ff'), ObjectId('68d6f22621e68be5b34eb500'), ObjectId('68d6f22621e68be5b34eb501'), ObjectId('68d6f22621e68be5b34eb502'), ObjectId('68d6f22621e68be5b34eb503'), ObjectId('68d6f22621e68be5b34eb504'), ObjectId('68d6f22621e68be5b34eb505'), ObjectId('68d6f22621e68be5b34eb506'), ObjectId('68d6f22621e68be5b34eb507'), ObjectId('68d6f22621e68be5b34eb508'), ObjectId('68d6f22621e68be5b34eb509'), ObjectId('68d6f22621e68be5b34eb50a'), ObjectId('68d6f22621e68be5b34eb50b'), ObjectId('68d6f22621e68be5b34eb50c'), ObjectId('68d6f22621e68be5b34eb50d'), ObjectId('68d6f22621e68be5b34eb50e'), ObjectId('68d6f22621e68be5b34eb50f'), ObjectId('68d6f22621e68be5b34eb510'), ObjectId('68d6f22621e68be5b34eb511'), ObjectId('68d6f22621e68be5b34eb512'), ObjectId('68d6f22621e68be5b34eb513'), ObjectId('68d6f22621e68be5b34eb514'), ObjectId('68d6f22621e68be5b34eb515'), ObjectId('68d6f22621e68be5b34eb516'), ObjectId('68d6f22621e68be5b34eb517'), ObjectId('68d6f22621e68be5b34eb518')], acknowledged=True)